#!/bin/bash

# 🦋 Butterfly Drop - Local Mobile Testing Script
# This script helps you test the app on your mobile device

set -e

echo "🦋 Butterfly Drop - Mobile Testing Setup"
echo "========================================"
echo ""

# Get local IP address
if command -v hostname &> /dev/null; then
    LOCAL_IP=$(hostname -I | awk '{print $1}')
elif command -v ip &> /dev/null; then
    LOCAL_IP=$(ip addr show | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | cut -d/ -f1 | head -1)
else
    echo "❌ Could not detect IP address automatically"
    echo "Please enter your laptop's IP address manually:"
    read LOCAL_IP
fi

echo "📱 Your laptop's IP address: $LOCAL_IP"
echo ""

# Update .env.local with correct IP
echo "📝 Creating .env.local with your IP..."
cat > .env.local << EOF
# Local Development Environment - LAN Testing
# Auto-generated by test-mobile.sh

# Your laptop's local IP address
VITE_SIGNALING_URL=ws://$LOCAL_IP:8080

# For production deployment, use .env with wss:// URL
EOF

echo "✅ Created .env.local"
echo ""

# Rebuild server
echo "🔨 Building server..."
cd server
pnpm build
cd ..
echo "✅ Server built"
echo ""

# Kill existing processes
echo "🧹 Cleaning up existing processes..."
pkill -f "node.*dist/index.js" 2>/dev/null || true
pkill -f "vite" 2>/dev/null || true
sleep 1

# Start server in background
echo "🚀 Starting signaling server..."
cd server
node dist/index.js > ../server.log 2>&1 &
SERVER_PID=$!
cd ..
sleep 2

# Check if server started
if ps -p $SERVER_PID > /dev/null; then
    echo "✅ Server started (PID: $SERVER_PID)"
else
    echo "❌ Server failed to start. Check server.log for errors"
    exit 1
fi

# Start frontend
echo "🎨 Starting frontend..."
pnpm dev --host > frontend.log 2>&1 &
FRONTEND_PID=$!
sleep 3

# Check if frontend started
if ps -p $FRONTEND_PID > /dev/null; then
    echo "✅ Frontend started (PID: $FRONTEND_PID)"
else
    echo "❌ Frontend failed to start. Check frontend.log for errors"
    kill $SERVER_PID 2>/dev/null || true
    exit 1
fi

echo ""
echo "=========================================="
echo "🎉 Setup Complete! Ready to test!"
echo "=========================================="
echo ""
echo "📱 Open on your mobile device:"
echo "   http://$LOCAL_IP:5173"
echo ""
echo "💻 Open on your laptop:"
echo "   http://localhost:5173"
echo ""
echo "🔍 Test signaling server:"
echo "   curl http://$LOCAL_IP:8080/health"
echo ""
echo "📊 View logs:"
echo "   tail -f server.log     (server logs)"
echo "   tail -f frontend.log   (frontend logs)"
echo ""
echo "🛑 To stop servers:"
echo "   kill $SERVER_PID $FRONTEND_PID"
echo "   OR press Ctrl+C and run: pkill -f 'node.*dist/index.js' && pkill -f vite"
echo ""
echo "⚠️  Make sure your mobile is on the same WiFi network!"
echo ""

# Wait for user
echo "Press Ctrl+C to stop all servers..."
trap "echo ''; echo '🛑 Stopping servers...'; kill $SERVER_PID $FRONTEND_PID 2>/dev/null || true; echo '✅ Servers stopped'; exit 0" INT TERM

# Keep script running
wait
